- documentation/docs/requirements/system-block-diagram.md
Importing Figure caused build errors in deployment.
> Removed Import for Image Captioning

- documentation/docs/requirements/general-requirements.md
Added our Tech Stack and Project Management Tools.
> Updates to General Requirements

- documentation/docs/requirements/system-overview.md
Removed word fluff from project abstract, focused on the features of the application.
> Revised project abstract GCCA-37

- documentation/docs/requirements/features-and-requirements.md
Removed the first two requirements in the Functional requirements section as they seemed more like user instructions rather than project requirements based on the feedback. Also, organized Functional and Nonfunctional requirements into common categories for better clarity.
> Features and Requirements revised

- documentation/docs/system-architecture/class-diagram.md
Based on the current progress, this is as much as we can show on our class diagram
> Base Class Diagram

- documentation/docs/system-architecture/sequence-diagrams.md
Created the base sequence diagram. Will need to be updated as we move forward.
> Sequence diagram

- documentation/docs/requirements/use-case-descriptions.md
Left old use case in for reference will remove later
> Update use-case-descriptions with feedback in class

- documentation/docs/system-architecture/design.md
> Update design.md, Reformatted

- documentation/docs/system-architecture/version-control.md
Refined verson control document explaining Github and repo structure.
> Version Control Document

- educode/package.json
- educode/src/extension.ts
- educode/src/index.ts
- educode/src/suggest.ts
- educode/yarn.lock
- server/db/router.py
Fix package errors in package.json and write docstrings and comments for frontend
> Add docstring frontend

- server/db/db.py
- server/requirements.txt
Created Database class with helper methods for interacting with a MongoDB database. It includes a connection setup method to initialize the MongoDB client and connect to the specified database. 
The send_code_snippet function to insert code snippets and a retrieve_code_snippets function to fetch snippets based on user ID.
> Added Database class with functions to send and retrieve data from MongoDB

- .github/workflows/ecudodeTest.yml
- educode/.gitignore
- educode/src/test/extension.test.ts
Workflow will execute tests in multiple environments when merging any changes to main
> Frontend Testing Automation

- educode/package-lock.json
- educode/package.json
- educode/src/extension.ts
- educode/yarn.lock
- server/ai/llm.py
- server/db/db.py
Upon starting the extension, user is forced to login with github.
> Github Login upon starting

- educode/package.json
- educode/src/extension.ts
- server/ai/llm.py
- server/db/db.py
- server/db/models.py
- server/db/router.py
Tracking Suggestions: The completionTracker now stores the suggestion presented to the user, including the suggestion text, position, and timestamp.
Logging Acceptance/Rejection: The extension logs whether the user accepted or rejected the suggestion, ensuring that only one of these events is logged per suggestion.
Event Listener for Text Changes: An event listener monitors text changes to detect when a suggestion is rejected by the user.
Server Communication: The extension sends detailed logs to the server, including the filename, position, and timestamp, for further analysis.
> Implemented suggestion logging

- documentation/docs/requirements/system-overview.md
May add more detail, but these updates give a more detailed overview of the architecture of our application
> updated sys overview

- educode/src/extension.ts
- server/db/db.py
- server/db/models.py
- server/db/router.py
Logs user input at a fixed interval
Logs userId, code, filename, timestamp
Logs data only if changes occur since the last recorded entry
> Implemented Interval Logging for User Input 

- educode/package.json
- educode/src/extension.ts
- educode/src/webViewHTML.ts
- educode/yarn.lock
- server/ai/llm.py
- server/ai/models.py
- server/ai/router.py
now includes new models for the Request and response of the askEducode route
New route called askEducode
New function to use a separate setup for the llm, instead of code responses, it will respond in markdown to display to the user
Disposable function holding the original unused Hello world function is replaced with an askEducode function that can be triggered by searching for the comang or using cmd + alt + u
> Create ask Educode Feature

- educode/src/extension.ts
- server/db/db.py
- server/db/models.py
- server/db/router.py
move Vincent's work from addingUsers to new branch due to merge conflicts with new changes
> move changes from addingUsers to new branch due to merge conflicts

- educode/src/extension.ts
Getting error with integer in database, so added toString() on account.id
> Added toString to session.account.id to fix error

- educode/src/extension.ts
- server/ai/llm.py
- server/ai/models.py
- server/ai/router.py
Allows users to get suggestions based on comments from the previous line, stops suggestor when a line is commented
> fix equality checks, create comment detection for python, and comment suggestions
